### ISSUE TITLE
Deprecation of context parameter

### ISSUE THREAD

**Issue by deejiw** [szkiba/xk6-jose#9]
I did try to build k6@0.46.0 with xk6-jose@v0.1.3 but failed to use the extension due to `Context.context` error.

To mitigate this, I did fork the repository and push the edit to address [changes](https://github.com/deejiw/xk6-jose/commit/06094174e6abbaf2d25cbd7c7e0bec59118f9476).

**Comment by tilln-kb** [comment]
@szkiba @mstoykov 
Perhaps the maintainers would accept a pull request based on @deejiw's fork to resolve this issue?

**Comment by szkiba** [comment]
This extension is deprecated. In the meantime, [k6 supports webcrypto](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/webcrypto/), it is advisable to use it in new tests.
If you need this extension because of your old tests or if you want to continue development, feel free to fork it.
